/*
 *  Copyright (C) 2025 Texas Instruments Incorporated
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *
 *    Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 *    Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the
 *    distribution.
 *
 *    Neither the name of Texas Instruments Incorporated nor the names of
 *    its contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 *  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 *  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 *  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 *  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 *  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 *  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 *  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 *  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 */

/**
 * \file   board_ecu.h
 *
 * \brief  This header file provides the API prototypes and necessary declarations for configuring the ECU.
 *
 * \details
 *        When an ECU instance or configuration is selected using the DM Power Configuration tool,
 *        the tool generates a corresponding #define. The user needs to pass this generated #define
 *        to the Board_ecuInit(uint32_t cfg) function to select the desired configuration.
 *
 * \note
 *        This header file is automatically generated by the DM Power Configuration tool.
 *
 */

#ifndef BOARD_ECU_H_
#define BOARD_ECU_H_

#ifdef __cplusplus
extern "C" {
#endif

/* ========================================================================== */
/*                             Include Files                                  */
/* ========================================================================== */

#include "board_cfg.h"

/* ========================================================================== */
/*                         Structure Declarations                             */
/* ========================================================================== */

/* None */

/* ========================================================================== */
/*                           Macros & Typedefs                                */
/* ========================================================================== */

/**
 * \anchor Board_EcuCfg
 *
 * \brief Configurations selected in DM Power Config Tool.
 *
 * This config defines is passed as cfg argument to Board_ecuInit to select a configuration.
 *
 * \note The instance names are generated based on the name of the instance in
 *       the DM Power Configuration tool.
 *       BOARD_ECU_NONE enables all clocks and sets PLLs defined in board_clock.c and board_pll.c
 */
#define  BOARD_ECU_NONE        (0U)
#define  BOARD_ECU_FC          (1U)
#define  BOARD_ECU_SRV         (2U)
#define  BOARD_ECU_AVP         (3U)

/* ========================================================================== */
/*                        Function Declarations                               */
/* ========================================================================== */

/**
* \brief Initializes the board with PLL and PSC configurations based on the use-case.
*
* \param cfg [IN] Configuration to select. Refer to \ref Board_EcuCfg.
*
* \return The status of the board initialization
*/
Board_STATUS Board_ecuInit(uint32_t cfg);

/* ========================================================================== */
/*                       Internal Function Declarations                       */
/* ========================================================================== */

/* None */

#ifdef __cplusplus
}
#endif

#endif
